### ISSUE TITLE
How config nvim-dap-python to use external_terminal ?

### ISSUE THREAD

**Issue by pittcat** [mfussenegger/nvim-dap-python#10]

**Comment by pittcat** [comment]
It works well after i add the snippets into my config
```
table.insert(dap.configurations.python, {
  type = 'python',
  request = 'launch',
  name = 'Launch file in externalTerminal',
  program = '${file}',   
  console = 'externalTerminal';
})
```

**Comment by mfussenegger** [comment]
You could also set the option in the `setup` call:

```lua
require('dap-python').setup(debug_py_python_path, { console = 'externalTerminal' })
```

**Comment by pittcat** [comment]
This solution can work well . Thank you for your reply and for your efforts with nvim-dap .

**Comment by jakkarn** [comment]
Mind if I ask a follow up on this issue? I tried to do this but I get the error that `Requested external terminal, but none configured. Fallback to integratedTerminal.` how do I configure it to open my standard terminal as an external terminal? I'm also using linux mint and not sure how to check what that terminal is.

**Comment by jakkarn** [comment]
I've tried adding these to my `dap.configurations.python`
```
console = "externalTerminal";
terminal = "gnome-terminal";
```
but I still get the error.

**Comment by mfussenegger** [comment]
> Mind if I ask a follow up on this issue? I tried to do this but I get the error that `Requested external terminal, but none configured. Fallback to integratedTerminal.` how do I configure it to open my standard terminal as an external terminal?

See `:help dap-terminal`
