### ISSUE TITLE
How to set current working directory ?

### ISSUE THREAD

**Issue by SamPosh** [mfussenegger/nvim-dap-python#101]
In my python file I am opening a file , the file path contains my_tool/input.yaml

/workspaces
  |__ my_tool
    |__ tool.py
    |__ input.yaml

I opened the file in neovim and execute the tool.py
```
f __name__ == "__main__":
    filepath = "my_tool/input.yml"
    with open(filepath, "r") as f:
        input_data = yaml.load(f, Loader=yaml.SafeLoader)
```
it fails as 
`
Thread stopped due to exception of type FileNotFoundError
`

But if i change the filepath to 'input.yml' then it works. Seems like current working directory is set to file path. 
Can I modify the cwd? How to do it? Is there an option available for it?

**Comment by lucaguarro** [comment]
sorry to open this back up again but if I am understanding correctly the configuration is global, right? Obviously, I want the working directory to be different from python project to python project so is there a way to configure it at the project level?

Thanks.
