### ISSUE TITLE
Error message has no line breaks

### ISSUE THREAD

**Issue by MisterSincere** [mfussenegger/nvim-dap-python#104]
Hello,
just set up your plugin and it was pretty easy. Now I have the problem that within a simple test program, where I just have an IndexError, the according error message goes right out of screen. Hence for example the stack trace is not readable.

Is there a configuration I can change for that? Is there a desired behavior for that?

It would be pretty nice to be able to read the error "inlined" in the code. Otherwise I just start the program normally and check the error message, which does not feel right.

**Comment by mfussenegger** [comment]
If you're referring to the error of an exception breakpoint you can use the neovim diagnostic api to show the full message.  E.g.: `:lua vim.diagnostic.open_float()`

If it's about repl output - there are open issues in nvim-dap, see:

- https://github.com/mfussenegger/nvim-dap/issues/737
- https://github.com/mfussenegger/nvim-dap/issues/1062
