### ISSUE TITLE
This function requires 1 argument(s) but instead it is receiving 0. [missing-parameter] ~Lua Diagnostics.

### ISSUE THREAD

**Issue by nyngwang** [mfussenegger/nvim-dap-python#106]
I have been bared with this error message for a long time. Could you help me identify whether or not it's a false alert? I can provide more info but I need to know what is needed in the first place, so feel free to let me know what should I provide for you to debug, thanks!

<img src="https://user-images.githubusercontent.com/24765272/236673257-ff6c7678-b278-48ea-8441-65f97082da24.png" width="700">

```
This function requires 1 argument(s) but instead it is receiving 0.
```

**Comment by mfussenegger** [comment]
Thanks for pointing out, fixed it with https://github.com/mfussenegger/nvim-dap-python/commit/51ecb08dbff57fca8add396b93dc765aba262e0a
