### ISSUE TITLE
Error executing vim.schedule lua callback: [...] /.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1329: Error running [...]/.local/share/nvim/mason/packages/debugpy/venv/bin/python: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by nyngwang** [mfussenegger/nvim-dap-python#107]
I got this error:

```
   Error  12:36:38 msg_show.lua_error Error executing vim.schedule lua callback: /Users/ningwang/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:493: ...wang/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1329: Error running /Users/ningwang/.local/share/nvim/mason/packages/debugpy/venv/bin/python: ENOENT: no such file or directory
stack traceback:
	[C]: in function 'trigger_run'
	/Users/ningwang/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:493: in function 'run'
	/Users/ningwang/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:406: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

This is my setup:

```lua
use {
  'mfussenegger/nvim-dap-python',
  dependencies = { 'mfussenegger/nvim-dap' },
  config = function ()
    local dappy = require('dap-python')
    dappy.setup('~/.local/share/nvim/mason/packages/debugpy/venv/bin/python')
    vim.keymap.set('n', '<Leader>dppm', function () dappy.test_method() end, G.NOREF_NOERR_TRUNC)
    vim.keymap.set('n', '<Leader>dppc', function () dappy.test_class() end, G.NOREF_NOERR_TRUNC)
    vim.keymap.set('x', '<Leader>dppx', function () dappy.debug_selection() end, G.NOREF_NOERR_TRUNC)
  end
}
```

I installed `debugpy` with mason.nvim.

**Comment by mfussenegger** [comment]
The error is pretty clear:

```
 Error running /Users/ningwang/.local/share/nvim/mason/packages/debugpy/venv/bin/python: ENOENT: no such file or directory
```

**Comment by nyngwang** [comment]
Hi, sorry for not being clear about the situation. The following message is optional, I just want to say that I'm responsible for all issues I created here.

When I encountered this bug, I did read the error message and checked that indicated path, i.e. `~/.local/share/nvim/mason/packages/debugpy/venv/bin/python`. The file exists. The dashboard of mason.nvim did show that I have `debugpy` installed. I also tried to cd into the folder to see what's going on. Finally, I resolved this hours ago by reinstalling everything inside the folder `~/.local`. I believe this could be related to the caching mechanism of lazy.nvim, not sure.

I planned to close this issue with not just the solution but also the insight to help any future user who will probably also run into this situation(since both plugins: lazy & mason are the most popular solutions recently). Anyway, hope you don't get annoyed by this issue. I just want to let you know I'm responsible for it. If I can find the reason that caused this problem, I will add comments here for reference.

**Comment by owod24** [comment]
Hi there, i'm currently facing this issue, can you go into more detail on how to solve it? I have checked to see if i spelt everything correctly and have restarted neovim multiple times but i  still get the error message.

**Comment by mairs8** [comment]
so am i

**Comment by nyngwang** [comment]
@owod24 @mairs8 Try avoid using the `~` shorthand(I'm still not sure). This is what I currently have in my dotfiles:

```
dappy.setup(vim.fn.stdpath('data') .. '/mason/packages/debugpy/venv/bin/python')
```
