### ISSUE TITLE
Windows venv detection

### ISSUE THREAD

**Issue by Balandino** [mfussenegger/nvim-dap-python#115]
Hello,

I setup dap-python and hit a problem detecting my virtual environment in Windows.  My setup is as follows:

```
require("dap-python").setup(vim.fn.getcwd() .. "\\Scripts\\" .. "python.exe")
table.insert(require("dap").configurations.python, {
	type = "python",
	request = "launch",
	program = "${file}",
	console = "integratedTerminal",
	name = "Launch file with autoReload",
	justMyCode = false,
	autoReload = {
		enable = true,
	},
})

require("dap-python").resolve_python = function()
	return vim.fn.getcwd() .. "\\Scripts\\" .. "python.exe"
end

```

However when I attempted to run dap it kept appending /bin/python to the debugger command.  I swapped out the is_windows() command from dap-python.lua (line 45)  from:

```
 local is_windows = function()
     return vim.loop.os_uname().sysname:find("Windows", 1, true) and true
 end
```

to the following:

```
local is_windows = function()
  return vim.fn.has("win32") == 1
end
```

and it worked perfectly, appending \Scripts\python as needed.  Unsure if this is a bug in my setup or the the plugin itself so reporting here.  When I ran the original code for is_windows()  it seemed to just return nil.

Please let me know if you require. more information and I'll see what I can do.

**Comment by mfussenegger** [comment]
Could you share the output of `:lua print(vim.loop.os_uname().sysname)`?

**Comment by Balandino** [comment]
Hello,

Sorry for the delay in getting back to you.  The output of that command is:

MINGW32_NT-10.0

My Neovim should just be the .msi for Windows downloaded from the official github,

**Comment by mfussenegger** [comment]
Thanks, I've changed the logic with https://github.com/mfussenegger/nvim-dap-python/pull/120
