### ISSUE TITLE
Custom visualization of dataframes

### ISSUE THREAD

**Issue by sotte** [mfussenegger/nvim-dap-python#116]
This is more a question than an issue. I'm wondering how one would go about implementing a custom widget/view for pandas dataframes. The default debug views don't really give you a nicely readable view of the the DF.
For displaying one could use e.g. https://github.com/MunifTanjim/nui.nvim/tree/main/lua/nui/table, but I'm not sure how this would fit into the DAP ecosystem. Do you have any pointers/ideas?

**Comment by mfussenegger** [comment]
You could create some custom functions that use the session to retrieve the variables and then render them in whatever way you want.

I played around a while ago with graphviz to visualize variables, maybe that gives you an idea how to use the API:

https://github.com/mfussenegger/dotfiles/blob/b4762410a523ca19bd08102e0ac4f2a592a1fe8c/vim/.config/nvim/lua/me/dap.lua#L7-L106

Some more pointers:

- You can make any kind of request using the `request` _method_ on the `session`. You get the session via `dap.session()`. The signature is `session:request(method_name, params, [callback])`. If you're in a coroutine, you can omit the callback and get a `err, result` tuple as result instead.
- The session has a `current_frame` property which contains a [StackFrame](https://microsoft.github.io/debug-adapter-protocol/specification#Types_StackFrame) if the session is stopped at a breakpoint.
- nvim-dap adds a `scopes` property to the `StackFrame`, which contains a list of [Scopes](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Scope)
- [evaluate](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Evaluate) could be useful if you want to evaluate arbitrary expressions

**Comment by sotte** [comment]
This is super helpful and way more than I was hoping for, thank @mfussenegger! This should be enough to build something.
