### ISSUE TITLE
Debugpy - Windows

### ISSUE THREAD

**Issue by msMatix** [mfussenegger/nvim-dap-python#118]
Hello,
I wanted to debug my application on windows with nvim-dap-python. However, I get the following warning message:
**The debug adapter did not respond. Either the adapter is slow (then wait and ignore) or there is a problem with your adapter in the 'python' configuration.** 

Furthermore I get with the cmd _DapShowLog_ the following hint:

```
[ ERROR ] 2023-09-19T09:22:46Z+0200 ] ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:1431 ]	"stderr"	{
  command = "C:\\Users\\xxx\\AppData\\Local\\nvim-data\\mason\\bin\\debugpy-adapter.CMD",
  type = "executable"
}	"^C"
```

However, my configuration works fine on my Linux system. I have now seen in some hints that there are issues with windows. 

My configuration is as follows:
```
return {
  {
    "mfussenegger/nvim-dap",
    optional = true,
    dependencies = {
      "mfussenegger/nvim-dap-python",
      -- stylua: ignore
      keys = {
        { "<leader>dPt", function() require('dap-python').test_method() end, desc = "Debug Method" },
        { "<leader>dPc", function() require('dap-python').test_class() end, desc = "Debug Class" }
      },
      config = function()
        local path = require('mason-registry').get_package('debugpy'):get_install_path()
        if vim.loop.os_uname().sysname:find("Windows") then
          require("dap-python").setup(path .. "dap-python" .. "python")
        else
          require("dap-python").setup(path .. "/venv/bin/python")
        end
      end,
    },
  },
}
```

Additionally, I use LazyVim framework. My guess is at the path. However, when I print the path in the setup method, I get the correct path. Can someone help me here?
If you need more information, please contact me.

Thanks in advance.

**Comment by heheda123123** [comment]
I have the same problem

**Comment by heheda123123** [comment]
Is this a bug? below code not have "Scripts"
![image](https://github.com/mfussenegger/nvim-dap-python/assets/97490782/426fba66-9a39-4112-bf3c-6b72427b9397)

**Comment by heheda123123** [comment]
Has the command line wrong?
![image](https://github.com/mfussenegger/nvim-dap-python/assets/97490782/5ebcabdf-9d4e-467b-b148-4ced16fcc749)
May be it should be ?
```
-m debugpy --listen localhost:5678 --wait-for-client myfile.py
```

**Comment by heheda123123** [comment]
If I use the config from here, it can debug normally, it should be a bug in nvim-dap-python
```
https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#python
```
![image](https://github.com/mfussenegger/nvim-dap-python/assets/97490782/5fc0ddc3-6828-48de-83ea-29736913a9cd)
my config
```
return {
  {
    "jay-babu/mason-nvim-dap.nvim",
    config = function(_, opts)
      local dap = require("dap")
      dap.adapters.python = function(cb, config)
        if config.request == "attach" then
          ---@diagnostic disable-next-line: undefined-field
          local port = (config.connect or config).port
          ---@diagnostic disable-next-line: undefined-field
          local host = (config.connect or config).host or "127.0.0.1"
          cb({
            type = "server",
            port = assert(port, "`connect.port` is required for a python `attach` configuration"),
            host = host,
            options = {
              source_filetype = "python",
            },
          })
        else
          cb({
            type = "executable",
            command = "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\python.exe",
            args = { "-m", "debugpy.adapter" },
            options = {
              source_filetype = "python",
            },
          })
        end
      end
      dap.configurations.python = {
        {
          -- The first three options are required by nvim-dap
          type = "python", -- the type here established the link to the adapter definition: `dap.adapters.python`
          request = "launch",
          name = "Launch file",

          -- Options below are for debugpy, see https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings for supported options

          program = "${file}", -- This configuration will launch the current file if used.
          pythonPath = function()
            -- debugpy supports launching an application with a different interpreter then the one used to launch debugpy itself.
            -- The code below looks for a `venv` or `.venv` folder in the current directly and uses the python within.
            -- You could adapt this - to for example use the `VIRTUAL_ENV` environment variable.
            local cwd = vim.fn.getcwd()
            if vim.fn.executable(cwd .. "/venv/bin/python") == 1 then
              return cwd .. "/venv/bin/python"
            elseif vim.fn.executable(cwd .. "/.venv/bin/python") == 1 then
              return cwd .. "/.venv/bin/python"
            else
              return "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\python.exe"
            end
          end,
        },
      }
    end,
  },
  {
    "CRAG666/code_runner.nvim",
    config = function(_, opts)
      require("code_runner").setup(opts)
      vim.api.nvim_create_autocmd("TermOpen", {
        group = vim.api.nvim_create_augroup("RunClose", { clear = true }),
        desc = "RunClose with q",
        callback = function()
          vim.keymap.set("n", "q", "<cmd>RunClose<cr>", { buffer = true })
        end,
      })
    end,
    keys = {
      { "<leader>cc", ":RunCode<cr>", desc = "RunCode" },
      { "<M-r>", ":RunCode<cr>", desc = "RunCode" },
    },
    opts = {
      filetype = {
        c = {
          "cd $dir ;",
          "gcc $fileName -o $fileNameWithoutExt" .. ".exe ;",
          "./" .. "$fileNameWithoutExt" .. ".exe",
        },
        cpp = {
          "cd $dir ;",
          "g++ $fileName -o $fileNameWithoutExt" .. ".exe ;",
          "./" .. "$fileNameWithoutExt" .. ".exe",
        },
        go = { "cd $dir ;", "go mod tidy;", "go run $dir" },
        lua = { "cd $dir ;", "lua $fileName" },
      },
    },
  },
}

```

**Comment by akthe-at** [comment]
> If I use the config from here, it can debug normally, it should be a bug in nvim-dap-python
> 
> ```
> https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#python
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/97490782/297693169-5fc0ddc3-6828-48de-83ea-29736913a9cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MTA1NzQsIm5iZiI6MTcwNzQxMDI3NCwicGF0aCI6Ii85NzQ5MDc4Mi8yOTc2OTMxNjktNWZjMGRkYzMtNjgyOC00OGRlLTgzZWEtMjk3MzY5MTNhOWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDE2Mzc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1OGVjNjMyMTYyOTljYTJjZTdhYzdkNTY0NGJhYzZmNTAzYjc5YzY4NjkxMjU3MGQ1MmZjOTU2ZmNlZGIzZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l7QwOC7xkoK4WvAWlsoLoMu9PnuURv-wFmlocKqp_mI) my config
> 
> ```
> return {
>    {
>     "jay-babu/mason-nvim-dap.nvim",
>     config = function(_, opts)
>       require("mason-nvim-dap").setup(opts)
>       local dap = require("dap")
>       dap.adapters.python = function(cb, config)
>         if config.request == "attach" then
>           ---@diagnostic disable-next-line: undefined-field
>           local port = (config.connect or config).port
>           ---@diagnostic disable-next-line: undefined-field
>           local host = (config.connect or config).host or "127.0.0.1"
>           cb({
>             type = "server",
>             port = assert(port, "`connect.port` is required for a python `attach` configuration"),
>             host = host,
>             options = {
>               source_filetype = "python",
>             },
>           })
>         else
>           cb({
>             type = "executable",
>             command = "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\pythonw.exe",
>             args = { "-m", "debugpy.adapter" },
>             options = {
>               source_filetype = "python",
>             },
>           })
>         end
>       end
>       dap.configurations.python = {
>         {
>           -- The first three options are required by nvim-dap
>           type = "python", -- the type here established the link to the adapter definition: `dap.adapters.python`
>           request = "launch",
>           name = "Launch file",
> 
>           -- Options below are for debugpy, see https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings for supported options
> 
>           program = "${file}", -- This configuration will launch the current file if used.
>           pythonPath = function()
>             -- debugpy supports launching an application with a different interpreter then the one used to launch debugpy itself.
>             -- The code below looks for a `venv` or `.venv` folder in the current directly and uses the python within.
>             -- You could adapt this - to for example use the `VIRTUAL_ENV` environment variable.
>             local cwd = vim.fn.getcwd()
>             if vim.fn.executable(cwd .. "/venv/Scripts/pythonw.exe") == 1 then
>               return cwd .. "/venv/Scripts/pythonw.exe"
>             elseif vim.fn.executable(cwd .. "/.venv/Scripts/pythonw.exe") == 1 then
>               return cwd .. "/.venv/Scripts/pythonw.exe"
>             else
>               return "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\pythonw.exe"
>             end
>           end,
>         },
>       }
>     end,
>   },
> 
> }
> ```

Using this config, and changing the paths to reflect my local machine resulted in being able to debug normally, without any external shell window from opening up. Thank YOU

**Comment by nlahmi** [comment]
Just ran into this issue as well. @akthe-at 's response helped point me in the right direction, but ultimately is not very portable. I managed to solve it with https://github.com/linux-cultist/venv-selector.nvim , just make sure to enable the `dap_enabled` option (and to activate a venv before debugging your code)

**Comment by ilovevim** [comment]
`> Just ran into this issue as well. [@akthe-at](https://github.com/akthe-at) 's response helped point me in the right direction, but ultimately is not very portable. I managed to solve it with https://github.com/linux-cultist/venv-selector.nvim , just make sure to enable the `dap_enabled` option (and to activate a venv before debugging your code)

Same problem, I use venv-selector too. I hooked a listener to change the dap pythonPath dynamically so there is no need to activate the venv anymore.

local dap = require("dap")

-- 当前项目根目录加入到系统环境变量PYTHONPATH，避免报错ModuleNotFoundError
dap.listeners.on_config["pythonpath_setup"] = function(config)
	config = vim.deepcopy(config)

	-- 调整Python配置
	if config.type == "python" then
		-- 设置debug解释器为当前插件选中的虚拟环境
		config.pythonPath = require("venv-selector").python()

		-- 确保 env 表存在
		config.env = config.env or {}
		-- 设置 PYTHONPATH 为当前工作目录
		config.env.PYTHONPATH = vim.fn.getcwd()
	end
	return config
end
