### ISSUE TITLE
Execute test in a class in pytest

### ISSUE THREAD

**Issue by vcoyette** [mfussenegger/nvim-dap-python#12]
When running a test mehod which is inside a test class in pytest, the test is not found by the executor.
Here is an example:
```python 
class TestFoo:
    def test_one(self):
        a = 1
        assert a == 1
```
When launching debugging on this method, I get the following output:
```
ERROR: not found: test.py::test_one_eq_one
(no name 'test.py::test_one_eq_one' in any of [<Module test.py>])
```

Locally I could solve this by uncommenting the line 166 of `dap-python.lua` and adding a condition:
```lua
      if classname then
        fqn = table.concat({path, classname, closest_function}, '::')
      else
        fqn = table.concat({path, closest_function}, '::')
      end
```
It works for my use case, however it is not perfect. Here is a failing example:
```python
class TestFoo:
    def test_one(self):
        assert 1 == 1

def test_two():
    assert 2 == 2
```
When running on test_two, here is the error:
```
Error: not found: test_class.py::TestFoo::test_two
```

**Comment by mfussenegger** [comment]
Hi and thanks for the detailed problem description.

Could you try with https://github.com/mfussenegger/nvim-dap-python/pull/13 ?
I think it should enable the class support and handle the `test_two` example that you gave.

**Comment by vcoyette** [comment]
Thank you for your quick answer, it works like a charm !
