### ISSUE TITLE
[Feature Request] `test_file`, `test_dir` & `test_all`

### ISSUE THREAD

**Issue by Rizhiy** [mfussenegger/nvim-dap-python#122]
Would be great if `test_file`, `test_dir` and `test_all` methods were added.

- `test_file` - `pytest <filename>`
- `test_dir` - `pytest <dirname filename>`
- `test_all` - `pytest .`

**Comment by mfussenegger** [comment]
You can create your own configuration entries for that. E.g, create a `.vscode/launch.json` like the following, or extend tthe dap.configurations.python list.

```
{
   "version": "0.2.0",
   "configurations": [
       {
           "type": "python",
           "request": "launch",
           "name": "Test all",
           "module": "pytest"
       },
       {
           "type": "python",
           "request": "launch",
           "name": "Test file",
           "module": "pytest",
           "args": [
             "${file}"
           ]
       }
   ]
}
```

Not warranted to built this in. `test_class` and `test_method` are different because they require figuring out the context.

**Comment by Rizhiy** [comment]
Thanks
