### ISSUE TITLE
regression on detection of python bin

### ISSUE THREAD

**Issue by mr-majkel** [mfussenegger/nvim-dap-python#126]
With the changes done in #121, `.env` is used as one of the potential candidates for the directory containing python binary, however it is quite common used as file for storing environment variables that can be automatically sourced by different frameworks and tools. These include docker-compose, as well as python packages like `python-dotenv`, or django.

I would like to suggest a change that would check if the file found is a directory before actually trying to use it for python binary lookup.

**Comment by mfussenegger** [comment]
Thanks for pointing out. I added an additional directory check: https://github.com/mfussenegger/nvim-dap-python/pull/128

If that still causes problem let me know - I'd have to add another check on the full python path
