### ISSUE TITLE
how to debug main method using pytest

### ISSUE THREAD

**Issue by Gaurang033** [mfussenegger/nvim-dap-python#135]
Hi Guys, 

I am trying to setup my neovim and trying to understand how to setup `dap-python` so can debug main method.  currently when I am trying to do that I am getting following message. 

```
platform darwin -- Python 3.12.1, pytest-8.1.1, pluggy-1.4.0
rootdir: /Users/fki/Documents/git/Demo
collected 0 items                                                              

```

**Comment by victorfernandesraton** [comment]
Coud you please give some details about how are you configure dap and code pattern here?

Since pytest using certain behavior , you should check pytest doc for folder name convensions

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-dap-python/issues/122#issuecomment-1908761345
