### ISSUE TITLE
Robotframework Support

### ISSUE THREAD

**Issue by fcancelinha** [mfussenegger/nvim-dap-python#147]
Is it possible to use this adapter to debug \ test RobotFramework files ?

If not, can you or anyone guide me into the right direction to make nvim-dap work with the robot framework ?

(thank you for a wonderful plugin @mfussenegger)

**Comment by mfussenegger** [comment]
I'm not really familiar with the robot framework.
It looks like you can run the `robot` module via debugpy with a `.vscode/launch.json` configuration like:

```json
{
   "$schema": "https://raw.githubusercontent.com/mfussenegger/dapconfig-schema/master/dapconfig-schema.json",
   "version": "0.2.0",
   "configurations": [
       {
           "type": "debugpy",
           "request": "launch",
           "name": "run:robot",
           "module": "robot",
           "args": ["${file}"],
           "justMyCode": false
       }
   ]
}
```

`debugpy` Won't be able to step through the robot test case but I suspect it should hit any code that's executed as part of it and allowing to step through that. But I didn't test it.
