### ISSUE TITLE
Lua version not up to date

### ISSUE THREAD

**Issue by JulesVerne22** [mfussenegger/nvim-dap-python#150]
When I try to install nvim-dap-python via lazy, I get the error that it requires lua version 5.1 and I'm using lua5.4. Why does it require an older version of lua? Thanks in advance!

**Comment by Kang-geophysics** [comment]
![image](https://github.com/mfussenegger/nvim-dap-python/assets/56065588/ddf8bd2c-1923-40aa-8da7-0c223d8c2f85)
Is this same problem?

**Comment by JulesVerne22** [comment]
Yeah

**Comment by JulesVerne22** [comment]
I think I just discovered that brew is just installing the wrong lua version for the luarocks version it installs.

**Comment by Kang-geophysics** [comment]
`brew install Lua@5.1` has been disabled. How can I downgrade the lua?

**Comment by JulesVerne22** [comment]
I was able to download and install lua5.1, probably could also manually install the correct version of luarocks. I'm just going to wait for brew to fix its installation though and leave python dap uninstalled until then.

**Comment by folke** [comment]
luarocks is no longer needed for `nvim-dap-python`. You can update lazy.nvim and close this issue...

**Comment by JulesVerne22** [comment]
@folke is correct. I'm closing the issue.
