### ISSUE TITLE
debugging pytest with playwright subprocess fails

### ISSUE THREAD

**Issue by orenherman** [mfussenegger/nvim-dap-python#152]
hi all, 
i have a big complex test suite based on pytest that launches a browser and orchestrates it with playwright
currently my settings for nvim-dap are:
``` 
{
  runner = 'pytest',
  python = '/Users/orenherman/.virtualenvs/debugpy/bin/python',
  dap = {
    python = { '-Xfrozen_modules=off', '--multiprocess', '--qt-support=auto' },
    console = 'integratedTerminal',
    justMyCode = false,
    stopOnEntry = true,
    subProcess = true,
  },
}
```
i can set breakpoints in the different entry points and it'll catch them, but once set inside the subprocess that orchestrates the browser (the actual test) - it will skip those and disconnect the debugger. 
i know this must be a debugpy issue (although i do manage to debut the subprocesses in vscode) but i wonder if i can get some guidance please?
** worth noting, that debugging with `subProcess = false` or just running the test works just fine 
ill try and post a small repo with playwright and pytest to reproduce

**Comment by orenherman** [comment]
possible workaround - setting the ` --numprocesses` to 1, will result in 1 and the debugger will catch the breakpoint.

**Comment by mfussenegger** [comment]
Would need a minimal reproduction.

**Comment by mfussenegger** [comment]
Closing for now - but would still take a closer look if anyone can provide a minimal reproduction
