### ISSUE TITLE
E5108: Error executing lua: ...local/share/nvim/lazy/nvim-dap-python/lua/dap-python.lua:434

### ISSUE THREAD

**Issue by NoBadorGood** [mfussenegger/nvim-dap-python#159]
when I trying to debug a simple python file,it makes a mistake
![image](https://github.com/user-attachments/assets/dfadfb42-4740-44f0-9280-6183ab5461e0)
i have no idea to fix it

**Comment by mfussenegger** [comment]
You get an error because you're using `test_method` in a file without test methods.

You'll need to use the `Launch file` configuration to debug regular files
