### ISSUE TITLE
Supporting debugpy complete override

### ISSUE THREAD

**Issue by mhkarimi1383** [mfussenegger/nvim-dap-python#171]
Hi

I want to be able to completely override debugpy path location but I'm able to only override python executable

for example in NixOS `python3 -m debugpy` will not work, but `debugpy` command itself will work

**Comment by mfussenegger** [comment]
The `debugpy` command currently doesn't expose a way to run the adapter. It's necessary to go through `python -m debugpy.adapter`.

If `debugpy` itself works that means there has to be some interpreter location where the `debugpy` module is available you should be able to use that.
