### ISSUE TITLE
continue() restarts execution

### ISSUE THREAD

**Issue by soumil-07** [mfussenegger/nvim-dap-python#19]
Everything else works (halting at breakpoints, inspecting variables) but continue() starts execution again instead of continuing. I'm using the default config from the README.

**Comment by mfussenegger** [comment]
Could you post the output of the log when this happens? You've to set the log level to trace to get enough information, see `:help dap.set_log_level()`

**Comment by soumil-07** [comment]
I have no idea how but it randomly started working a few days after my issue. Sorry for the inconvenience!
