### ISSUE TITLE
Not debugging, throwing this error

### ISSUE THREAD

**Issue by Zigrino** [mfussenegger/nvim-dap-python#24]
![Screen Shot 2021-08-10 at 10 12 24 PM](https://user-images.githubusercontent.com/56608462/128959297-7b88ecbe-2da8-479c-a56a-eef4118ea948.png)

I'm not quite sure what this means, and which directory it's complaining about.

**Comment by mfussenegger** [comment]
Could you share some steps to reproduce this? I've no idea what you do to end up receiving this error.

**Comment by Zigrino** [comment]
I set up the code as per instructions, except I installed debugpy globally and changed the directory in the settings accordingly. I tried to test the plugin by setting a breakpoint and then running the debugger with :lua require'dap'.continue and it threw me this error. This error did go away after a couple seconds and was replaced with this one:

![Screen Shot 2021-08-11 at 2 20 46 PM](https://user-images.githubusercontent.com/56608462/129082453-eca76dc4-226d-4d98-ae1b-4ffcc721a8b9.png)

I'm on macos, I'm not sure if that matters.

**Comment by mfussenegger** [comment]
Could you post the log file? (See `:help dap.set_log_level()`)

The only two places in neovim that throw a "expected valid directory" message are related to the `cwd` property of `termopen` or `jobstart`. 

nvim-dap doesn't use `jobstart`, but only `termopen` for the integrated terminal and it defaults to the current working directory, so I'm not sure how/why that would cause a failure - unless you changed the default value?

**Comment by Zigrino** [comment]
I was cd'ed into a folder while trying to debug, maybe that was the problem?

**Comment by Zigrino** [comment]
yeah it doesn't throw an error when I edited the file from home directory

**Comment by Zigrino** [comment]
also, is it possible to view variable values and stuff like that using this debugger?

**Comment by mfussenegger** [comment]
> also, is it possible to view variable values and stuff like that using this debugger?

Please have a look at the readme of [nvim-dap](https://github.com/mfussenegger/nvim-dap) and the help page. It is all documented.
