### ISSUE TITLE
Is it possible to use it with the UI plugin?

### ISSUE THREAD

**Issue by al-stefanitsky-mozdor** [mfussenegger/nvim-dap-python#27]
Hi! Is it possible to use it with the UI plugin?

Opened repl while running method / class is not the same as repl from the UI plugin.

How I can attach a running test to the [dapui_repl](https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/elements/repl.lua#L6)?

**Comment by al-stefanitsky-mozdor** [comment]
But it (this package) opens another REPL pane, not attached to the UI REPL pane.

**Comment by al-stefanitsky-mozdor** [comment]
![ex](https://user-images.githubusercontent.com/93194623/139582795-e6cce17f-8b37-4adc-bc0c-0ffe18dc1b48.png)

**Comment by mfussenegger** [comment]
That's not the REPL but the terminal running your application. dap-ui uses the nvim-dap REPL and doesn't have it's own. 

You can call `setup` with optional options to change the console setting:

```lua
require('dap-python').setup('~/.virtualenvs/tools/bin/python', { console = 'internalConsole' })
```

See also `:help dap-terminal`

**Comment by mfussenegger** [comment]
I assume this is resolved(?)
