### ISSUE TITLE
FileNotFoundError - no such file or directory

### ISSUE THREAD

**Issue by black-eagle17** [mfussenegger/nvim-dap-python#29]
Hello, I am trying to debug a python application. I am using nvim-dap-python as the configuration for nvim-dap however I am getting this error when  I try to start the debugger as shown in the image below.

![image](https://user-images.githubusercontent.com/37980286/145942728-53562e8b-c081-4cfb-82fa-13ec93234efe.png)

The project is running in a virtual environment.
There should be only one `src` directory in the path: '/home/deandre/dev/DataVerse/src/src/main.py'
Any help will be appreciated, thanks.

**Comment by mfussenegger** [comment]
Are both nvim-dap and nvim-dap-python up2date? 

There were some changes how `${file}` gets expanded: 

https://github.com/mfussenegger/nvim-dap/pull/353
https://github.com/mfussenegger/nvim-dap-python/pull/28

**Comment by mfussenegger** [comment]
Closing, I assume this is resolved
