### ISSUE TITLE
Tree in `test_method` is not returned correctly after API changes in Neovim

### ISSUE THREAD

**Issue by stephan-hesselmann-by** [mfussenegger/nvim-dap-python#4]
After this commit in Neovim master https://github.com/neovim/neovim/commit/1a631026a942b3311adec0bee6d9b0b932c5de31 `parser:parse()` now returns a table of trees. This breaks `test_method()`, which assumes that a single tree is returned. See https://github.com/mfussenegger/nvim-dap-python/blob/master/lua/dap-python.lua#L109.

**Comment by mfussenegger** [comment]
Thank you for pointing out, I've merged a fix
