### ISSUE TITLE
unittest ValueError: Empty module name

### ISSUE THREAD

**Issue by rhinoxi** [mfussenegger/nvim-dap-python#51]
Hi,
I'm using `unittest` and have a project with following structure:
```
.
├── proj
│   ├── __init__.py
│   ├── some_func.py
└── tests
    ├── __init__.py
    ├── test_some_func.py
```
When I open `test_some_func.py` and run `:lua require('dap-python').test_method()`, it works fine.
But If I open some other file first, then switch to `test_some_func.py` file, and run `:lua require('dap-python').test_method()`, it said `ValueError: Empty module name`.

So I looked into the code.
https://github.com/mfussenegger/nvim-dap-python/blob/2911f31f0ac830b95112a642a0fccd2b1a5d967a/lua/dap-python.lua#L70

the code above returns `tests.test_some_func` if I open `test_some_func.py` directly.
but returns `.Path.To.Project.tests.test_some_func` if I switch to `test_some_func.py` from other file.

So I googled a bit, and found changing the code to the following works fine for me
```
local path = vim.fn.expand('%:p:~:.:r:gs?/?.?')
```

Since I'm not so familiar with the vim/nvim plugin thing, can you guys confirm this or if I'm doing anything wrong?

Thanks.

**Comment by mfussenegger** [comment]
Are you opening neovim outside of the project directory?

`'%:p:~:.:r:gs?/?.?'` looks a bit redundandent.  `:p` turns the path into an absolute path, `:~` makes it relative to the home directory, `:.` makes it relative to the current directory. Those are kinda incompatible with each other.

See `:help filename-modifiers`

**Comment by rhinoxi** [comment]
Thanks @mfussenegger . 
> '%:p:~:.:r:gs?/?.?' looks a bit redundandent.

Yes, `%:p:~:.:r:gs?/?.?` and `%:.:r:gs?/?.?` are returning the same results.

> Are you opening neovim outside of the project directory?

No, I don't think so. 

Let me use https://github.com/navdeep-G/samplemod to show the detail.

```
cd /Users/lds
git clone git@github.com:navdeep-G/samplemod.git
cd samplemod/sample
nvim core.py
```

Then use `:e tests/test_basic.py` to switch to the test file, and running the following command get different results:
- `:echo expand('%:r:gs?/?.?')` get `.Users.lds.samplemod.tests.test_basic`
- `:echo expand('%:.:r:gs?/?.?')` get `tests.test_basic`

If I want to get `:lua require('dap-python').test_method()` works fine, I think the second one is necessary.

**Comment by rhinoxi** [comment]
ok, I'll try to figure out which plugin or config is causing this behavior.

**Comment by rhinoxi** [comment]
It seems like this [project.nvim](https://github.com/ahmedkhalf/project.nvim) plugin is changing the working directory automatically, so that I can use `:e tests/test_basic.py` to switch when opening nvim in `samplemod/sample`.

**Comment by rhinoxi** [comment]
[[pyright] Python files are opened using a different path than the one I typed](https://github.com/neovim/nvim-lspconfig/issues/1829)
[When customizing root_dir, buffer names end-up being absolute, but only in pyright](https://github.com/neovim/nvim-lspconfig/issues/1851)
it seems to be a behavior of pyright.
I'll close this and send a PR.
