### ISSUE TITLE
Docker  + pytest example

### ISSUE THREAD

**Issue by eelkeh** [mfussenegger/nvim-dap-python#54]
I looked through the issues but could not find a recent enough example of setting dap up with `pytest` running in a Docker container. If someone has an example of how to set this up, it would be greatly appreciated!

**Comment by mfussenegger** [comment]
See https://github.com/microsoft/debugpy/wiki/Debugging-over-SSH and https://github.com/mfussenegger/nvim-dap/wiki/Local-and-Remote-Debugging-with-Docker

My personal recommendation would be to not use docker for the apps you're debugging, but only for 3rd party dependencies. Saves you lots of headaches.
