### ISSUE TITLE
[Feature Request] Tox support

### ISSUE THREAD

**Issue by holmanb** [mfussenegger/nvim-dap-python#63]
Is there any interest in integrating tox support?

Are there any technical blockers?

I'm considering writing my own custom runner, but if I'm going to do that anyways I might as well submit a PR so others may use it.

Maybe this has already been done this and is interested in submitting their work?

Please let me know your thoughts.

**Comment by mfussenegger** [comment]
> Is there any interest in integrating tox support?

It would be in scope of the plugin, so I'd accept a PR that adds it - assuming it fits the `M.test_runners` extension point.

> Are there any technical blockers?

Not that I'm aware of.

**Comment by mfussenegger** [comment]
I just had a closer look at this and I didn't get the impression that it would fit the current test_runners model.

I'm closing this for now but I'm still open to inputs that explain workflows and use-cases in some detail
