### ISSUE TITLE
Can work with gpu(cuda)

### ISSUE THREAD

**Issue by sisrfeng** [mfussenegger/nvim-dap-python#68]
I meet the error `No stopped threads. Cannot move`  in the line `input.cuda()`  (3rd line)

```
 with torch.no_grad():
     for batch_idx, (input, _) in enumerate(loader):
         input  = input.cuda()
         guess = model(input)
         #topk = guess.topk(k)[1]
         prob.append( guess.cpu().numpy() )

         # measure elapsed time
         batch_time.update( time.time() - end )
         end = time.time()
```
But before that, the following line works well:
```
model = model.cuda()
````

**Comment by mfussenegger** [comment]
> No stopped threads. Cannot move

Indicates that the debugger is not stopped at a breakpoint, but still running. Maybe you just have to wait longer, or it's waiting for some input? I have no idea what `input.cuda()` does.

If it really isn't progressing, it's probably an issue with debugpy itself, not with nvim-dap-python

**Comment by nyngwang** [comment]
@sisrfeng Did you solve it eventually? I'm also setting up nvim-dap for PyTorch recently. It will be great if you could share some insights on this. Thanks!

**Comment by sisrfeng** [comment]
> @sisrfeng Does pudb work well with PyTorch? (probably the last question, thanks!)

Mostly.
But it sometimes may fail when using multiple GPUs or multi-process.

**Comment by nyngwang** [comment]
@sisrfeng Thanks for your kindness :) I resolved it days ago. You're right, the configuration isn't the point. I used the default config provided by nvim-dap-python for debugpy. (No more problems on this thread!)

**Comment by sisrfeng** [comment]
> he configuration isn't the point. I used the default config provided by nvim-dap-python for debugpy. (No more problems on this thread!)

You this repo can work with gpu now ?! I tried but failed some days ago.
