### ISSUE TITLE
Can't cleanly exit debugging

### ISSUE THREAD

**Issue by proofer** [mfussenegger/nvim-dap-python#73]
nvim-dap-python is great but -- while I'm sure this is user ignorance rather than a real issue -- I'm unable to stop debugging and continue to edit my source file. The debugger window closes, but then in my source file any simple normal mode command (e.g., 'j' to move the cursor down) executes but then goes into insert mode.

Thrashing around as we newbies do, I tried a keymap to `function() require('dap').disconnect() end` but using it doesn't seem to matter.

**Comment by mfussenegger** [comment]
> But then in my source file any simple normal mode command (e.g., 'j' to move the cursor down) executes but then goes into insert mode.

You might have some `TermOpen` autocmds setup that enter insert mode automatically. nvim-dap opens a terminal if using `integratedTerminal` (which nvim-dap-python defaults to). This terminal also triggers a `TermOpen` event.
