### ISSUE TITLE
run dap with debugger disabled / bypassed? 

### ISSUE THREAD

**Issue by gminorcoles** [mfussenegger/nvim-dap-python#76]
Hi,
 I posted about this on the neovim subreddit but got no responses so I will bother you here with this question. I would like to re-use the dap settings I have setup for python to run the code but without invoking the debugger. This is a common workflow for me in PyCharm, the run config and the debug config can have the same parameters and you use the same interface to invoke them. I think I can figure this out from reading the code but I would be grateful if someone could help me determine whether this is something I can configure without changing any code.

**Comment by mfussenegger** [comment]
Not sure if I understand you correctly, but there is a `noDebug` option for the `:h dap-configuration`. For example:

```lua
local dap = require('dap')
if not dap.configurations.python then
  dap.configurations.python = {}
end
table.insert(dap.configurations.python, {
  type = 'python',
  request = 'launch',
  name = 'Run file',
  program = '${file}',
  noDebug = true,
})
```
