### ISSUE TITLE
Default configuration for remote attach with path mappings

### ISSUE THREAD

**Issue by gio8tisu** [mfussenegger/nvim-dap-python#81]
My workflow usually involves docker containers, which its file structure doesn't match the one on the host machine. This forces me to add a custom configuration to define a path mapping between the host machine and the container in order to attach the debugger.

Currently this is my version of said configuration:
```lua
table.insert(require("dap").configurations.python, {
  type = 'python';
  request = 'attach';
  name = 'Attach remote (with path mapping)';
  connect = function()
    local host = vim.fn.input('Host [127.0.0.1]: ')
    host = host ~= '' and host or '127.0.0.1'
    local port = tonumber(vim.fn.input('Port [5678]: ')) or 5678
    return { host = host, port = port }
  end;
  pathMappings = function()
    local cwd = '${workspaceFolder}'
    local local_path = vim.fn.input('Local path mapping [' .. cwd .. ']: ')
    local_path = local_path ~= '' and local_path or cwd
    local remote_path = vim.fn.input('Remote path mapping [.]: ')
    remote_path = remote_path ~= '' and remote_path or '.'
    return {{ localRoot = local_path, remoteRoot = remote_path }, }
  end
})
```
Which defaults to mapping the current working directories of the host and container.

I think a similar config could be added or replace the current `'Attach remote'` config with this one (maybe defaulting to an empty pathMapping).

I have very little experience with lua, but I could open a PR and do the necessary changes with some help.

Thanks for your awesome plugins, btw!

**Comment by mfussenegger** [comment]
I'd rather not extend the default configurations further. It's easy enough to add custom ones and if you have pathMappings it is probably worth creating per project `launch.json` files to avoid the input prompt each time you're starting a debug session.

**Comment by gio8tisu** [comment]
Thanks for the reply @mfussenegger , could you please explain the launch.json bit in more detail (or provide some documentation link)?

**Comment by mfussenegger** [comment]
> Thanks for the reply @mfussenegger , could you please explain the launch.json bit in more detail (or provide some documentation link)?

See `:help dap-launch.json`
