### ISSUE TITLE
Debugging a python module

### ISSUE THREAD

**Issue by d0nker420** [mfussenegger/nvim-dap-python#82]
Hey I'm new to using nvim-dap-python and am wondering how I should go about debugging a module in python that I typically launch via the python -m module_name command. Basically how to debug code run via the __init__ file while retaining the path of the superseding directory.

Thanks :)

**Comment by mfussenegger** [comment]
You can create a `:h dap-configuration` entry or `launch.json` (`:h dap-launch.json`) where you set the `module` property. See https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings for all configuration options.

**Comment by d0nker420** [comment]
@mfussenegger thanks a lot, appreciate it.
