### ISSUE TITLE
Duplicate entries after reloading configuration

### ISSUE THREAD

**Issue by Maritsu** [mfussenegger/nvim-dap-python#86]
After reloading my Neovim configuration file (`:so $MYVIMRC`), the debugger entries begin to duplicate - another whole set of entries after each reload. 

(apologies for the weird lines, scrot is acting up)  
- no reloads: 4 options (default)
![no reloads: 4 options](https://user-images.githubusercontent.com/66056347/219054774-48a1ab36-e318-43b7-969c-04bfae0b79e5.png)
- after reload: 8 options (each option appears twice)
![after reload: 8 options (each option appears twice)](https://user-images.githubusercontent.com/66056347/219054909-a43a74e7-fadf-4668-bdbc-794d2f957cb8.png)
- after one more reload: 12 options
![after one more reload: 12 options](https://user-images.githubusercontent.com/66056347/219055683-3884c249-2a7b-472c-a097-0759e2eea181.png)

**Comment by mfussenegger** [comment]
Yes, setup adds additional entries without reseting the existing entries. You'd need to clear them - e.g by setting `dap.configurations.python = {}`
