### ISSUE TITLE
Test runner "unittest" not working on windows.

### ISSUE THREAD

**Issue by BartSte** [mfussenegger/nvim-dap-python#91]
The regex depicted in yellow does not parse the backward slashed used by windows into periods:

![IMG_20230302_161248.jpg](https://user-images.githubusercontent.com/62509788/222469066-bc306a25-b4df-4984-995f-e5ef246573f4.jpg)

As a result, no tests can be executed using dap. A workaround is to replace the line by:
``` lua
local path = vim.fn.expand('%:.:r:gs?\\(/\\|\\\\\\)?.?')
```

**Comment by mfussenegger** [comment]
Could you create a PR to handle this differently on windows? I don't use windows and support is best-effort by community contributions.

**Comment by mfussenegger** [comment]
Closing as https://github.com/mfussenegger/nvim-dap-python/pull/96 got merged
