### ISSUE TITLE
django ValueError: Empty Module Name

### ISSUE THREAD

**Issue by moosbruggerj** [mfussenegger/nvim-dap-python#92]
Hi,

Debugging a test with `test_method` raises the same error as in #51 when used with [https://github.com/nvim-lua/kickstart.nvim](kickstart.nvim).

The fix for #51 is currently only applied for the `unittest` case, not the `django` one. On my local setup copying the fix resolved the issue.

**Comment by mfussenegger** [comment]
Could you create a PR to fix it for django too?
