### ISSUE TITLE
setting option justMyCode

### ISSUE THREAD

**Issue by jfmoulin** [mfussenegger/nvim-dap-python#95]
Hello, I am probably looking for the obvious but
 my google skills do not seem to bring an answer to my problem:
I would like to set justMyCode=false in order to debug external packages.

My init.lua contains the following:

    require('dap-python').setup('/usr/bin/python3')
    local dap, dapui =require("dap"),require("dapui")
     require('dap').set_exception_breakpoints({"raised", "uncaught"})
    table.insert(require('dap').configurations.python, {
    type = 'python',
    request = 'launch',
     program = '${file}',
     -- ... more options, see https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings
     justMyCode = false
     })

I tried putting some breakpoints in the `__init__.py` of numpy but I get the message:
`Frame skipped from debugging during step-in.
Note: may have been skipped because of "justMyCode" option (default == true). Try setting "justMyCode": false in the debug configuration (e.g., launch.json).
`

Does this option nead the launch.json ? I think everything should be configurable from lua....

**Comment by SamPosh** [comment]
@jfmoulin have you found a solution for it?

**Comment by jfmoulin** [comment]
Hello @SamPosh,
I had not, but gave it another shot when I saw your question...
This works:


```
-- dap
require('dap-python').setup('/usr/bin/python3')
local dap, dapui =require("dap"),require("dapui")
 
-- when to stop on exception (uncaught is providing post mortem debugging) (see dap-api)
require('dap').set_exception_breakpoints({"raised", "uncaught"})

require('dap').configurations.python = {
    {type = 'python',
      request = 'launch',
      name = 'My custom launch configuration',
      justMyCode = false,
      program = '${file}',
    },
}
```

the table.insert was the problem.
Thanks for pinging me ;0)
Hope this helps you too.
I really need to dive into lua now.

**Comment by lucasrcezimbra** [comment]
I solved it by changing my key bindings that run the tests. `test_method` and `test_class` receive an `opts` parameter.

```lua
lvim.keys.normal_mode["<leader>dm"] = ":lua require('dap-python').test_method({ config = { justMyCode = false } })<CR>"
lvim.keys.normal_mode["<leader>dl"] = ":lua require('dap-python').test_class({ config = { justMyCode = false } })<CR>"
```
